### ISSUE TITLE
`fs` (`fs_mock`) can not have instances

### ISSUE THREAD

**Issue by anonghuser** [browser-fs/core#25]
Currently you can create instances of any specific backend, either directly via the class constructors/factory methods or via the `getFileSystem` export.
However these are not quite the same as the `fs` or `default` export of  `browserfs`, which seems to be just a module keeping its state as local variables and exporting functions instead of an object instance of a backend class.
Also the MountableFileSystem class has been removed, its functionality taken over by the singleton `fs` export. This means it is impossible to create a second instance of a filesystem that mounts other filesystems.

What is the reason for this design? Would you consider changing it to support instances of the main object?

**Comment by anonghuser** [comment]
As a side note, I'd also like if the default initialization of the `fs` singleton with an `InMemory` root can be prevented. Yes, you can reconfigure it to anything else, but it still feels like the module did some pointless action first. I guess I just want to create my objects explicitly. It's not a big deal and I don't have a well-defined reason for it, so I won't post an issue, but I'm curious about opinions on the matter.

**Comment by anonghuser** [comment]
In theory singleton-like modules can still have instances if they are imported with a different query string. This works even in node for file imports, but not for bare module specifiers. It also fails when there are whole dependency chains that need to be instanced and not simple modules.
It's not a solution, but it can be a hacky workaround in the browser with a bundled version of the module.

**Comment by dr-vortex** [comment]
Also, the emulated API is different from the internal API (so that backend implementations do not need to handle compatibility, arguments, callbacks, etc.)
