### ISSUE TITLE
Define `BaseFileSystem.Create` 

### ISSUE THREAD

**Issue by anonghuser** [browser-fs/core#27]
`Create` static factory method is used instead of directly the constructor to support async initialization. But the base class does not define it, so when you inherit it and try to use your custom backend, you get `[TypeError: n.Create is not a function]`
Perhaps a standard definition should be provided in the base class, and extending classes would only have to override it if they want to do something special. It can refer to the current class via `this` so it will work in extending classes without overriding.

The current approach of `public static Create = CreateBackend.bind(this)` in extending classes does not work well if they are further extended - they use the constructor of the class in which the property was defined, not the extending one. Instead, perhaps use something like `public static Create(...args) {return CreateBackend.call(this, ...args)}` for minimal refactoring, or directly inline the code of `CreateBackend` as it seems pointless to have it as a separate export (except for backwards compatibility, but was it part of the API in jvilk's version?). Overrides that need to delegate to it can use `super.Create.call(this, ...args)`.

**Comment by dr-vortex** [comment]
It is intended to be defined by `BackendConstructor`s. Classes intended for internal use or convenience (e.g. `BaseFileSystem` and `SyncStore`) are not meant to be created by end users and therefore do not have a `Create` method.
