### ISSUE TITLE
`browser` and `exports` fields in `package.json`

### ISSUE THREAD

**Issue by anonghuser** [browser-fs/core#28]
To make the module easily usable in a browser from CDNs like unpkg and jsdeliver, add a `browser` field pointing to the bundled `dist/browser.min.js`.

To future-proof it for when these CDNs start supporting the new `exports` field (https://nodejs.org/api/packages.html#conditional-exports), add it as well:
```
"exports": {
  "import": {
    ".": "./dist/index.js",
    "./*": "./dist/*"
  },
  "default": "dist/browser.min.js"
},
```

**Comment by anonghuser** [comment]
Might want to add more entries for the subdirectories to map to their `index.js` since that's not done by default when you have `exports` field

**Comment by dr-vortex** [comment]
Since the `browser.min.js` has browser specific behavior (by assigning to a BFS global object) it  does not have types and doesn't support tree shaking. This means it should not be used for the default export.

**Comment by anonghuser** [comment]
with that definition it will only be used for the default export in environments that do not support `import`

**Comment by dr-vortex** [comment]
`require` would return the browser code, which is not compatible.

**Comment by anonghuser** [comment]
why is it not compatible?
