### ISSUE TITLE
Question: browser-fs IRC?

### ISSUE THREAD

**Issue by knackstedt** [browser-fs/core#31]
I'm really excited for the new version of browser-fs that's coming out. Is there any IRC chats (discord/slack etc) for this project?

I'm willing to create a Discord server if there's an appetite for it

**Comment by dr-vortex** [comment]
I don't believe there is a discord server or slack project for browserfs. I would be willing to create one after I finish some of the more pressing issues.

**Comment by knackstedt** [comment]
I can offer myself to make a Discord server for it -- making you and whoever else you specify an admin/team member.
If you want to create it, it's no big deal -- I'm just trying to help out :)

**Comment by dr-vortex** [comment]
@knackstedt,

I've made a discord server for BrowserFS. You can join here: https://discord.gg/CxYFAfsV5X
