### ISSUE TITLE
fsPromises.open() should return FileHandle

### ISSUE THREAD

**Issue by yoursunny** [browser-fs/core#32]
In [Node.js API docs](https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fspromises_open_path_flags_mode), `fs.promises.open(path, flags[, mode])` should return a Promise that resolves to `FileHandle` object.
However, BrowserFS is returning a Promise that resolves to a number.
https://github.com/browser-fs/core/blob/50ed605aa74987ee9824d34fc64a9b027a81ac90/src/emulation/promises.ts#L135-L138

**Comment by dr-vortex** [comment]
Fixed in 584f581
